Repository pokt-network/pocket, pull requests merged in 2022-11, with the labels that each got.

#306 [DOCUMENT] Interfaces for the M3 Relay Protocol (issue-#265)
  utility/doc/CHANGELOG.md
  utility/doc/PROTOCOL_RELAY.md
  utility/doc/PROTOCOL_SESSION.md
  utility/service/service.go
Labels: documentation

#332 [Persistence] TxIndexer to StateHash Bridge (Issue-#315)
  consensus/CHANGELOG.md
  consensus/block.go
  consensus/consensus_tests/utils_test.go
  consensus/helpers.go
  consensus/hotstuff_leader.go
  consensus/hotstuff_replica.go
  consensus/module.go
  persistence/CHANGELOG.md
  persistence/block.go
  persistence/context.go
  persistence/db.go
  persistence/indexer/doc/README.md
  shared/modules/consensus_module.go
  shared/modules/persistence_module.go
  shared/modules/utility_module.go
  utility/actor.go
  utility/block.go
  utility/doc/CHANGELOG.md
  utility/test/block_test.go
  utility/test/transaction_test.go
  utility/transaction.go
  utility/types/mempool.go
Labels: consensus, persistence, priority:high

#337 [Core] General Fixes to make LocalNet more reliable
  Makefile
  build/config/config1.json
  build/config/config2.json
  build/config/config3.json
  build/config/config4.json
  build/config/genesis.json
  consensus/debugging.go
  consensus/hotstuff_handler.go
  consensus/module.go
  consensus/pacemaker.go
  consensus/types/errors.go
  p2p/raintree/addrbook_utils.go
  p2p/raintree/network.go
  p2p/raintree/peers_manager.go
  p2p/raintree/target.go
  persistence/debug.go
  persistence/module.go
Labels: bug, code health

#341 [Utility] Tiny fix improvement
  utility/test/actor_test.go
  utility/test/block_test.go
Labels: utility, code health, testing

#176 [Utility] Local Proof of Stake CLI - RPC server [part 2/2] - Issue #112
  Makefile
  app/app.go
  app/pocket/doc/CHANGELOG.md
  app/pocket/doc/README.md
  app/pocket/main.go
  build/config/config1.json
  build/config/config2.json
  build/config/config3.json
  build/config/config4.json
  build/deployments/docker-compose.yaml
  consensus/consensus_tests/utils_test.go
  consensus/leader_election/module.go
  consensus/module.go
  consensus/pacemaker.go
  go.mod
  go.sum
  p2p/module.go
  persistence/module.go
  rpc/doc/CHANGELOG.md
  rpc/doc/README.md
  rpc/handlers.go
  rpc/module.go
  rpc/noop_module.go
  rpc/server.go
  rpc/types/proto/rpc_config.proto
  rpc/v1/openapi.yaml
  runtime/config.go
  runtime/docs/README.md
  shared/bus.go
  shared/modules/bus_module.go
  shared/modules/consensus_module.go
  shared/modules/rpc_module.go
  shared/modules/types.go
  shared/node.go
  telemetry/module.go
  telemetry/noop_module.go
  telemetry/prometheus_module.go
  utility/module.go
Labels: core, priority:high, tooling, client

#320 Ticket #211: finding unnecessary public functions in the Persistence Module
  .gitignore
  docs/development/FAQ.md
  persistence/CHANGELOG.md
  persistence/account.go
  persistence/application.go
  persistence/block.go
  persistence/db.go
  persistence/docs/CHANGELOG.md
  persistence/fisherman.go
  persistence/genesis.go
  persistence/gov.go
  persistence/service_node.go
  persistence/shared_sql.go
  persistence/test/application_test.go
  persistence/test/fisherman_test.go
  persistence/test/generic_test.go
  persistence/test/service_node_test.go
  persistence/test/validator_test.go
  persistence/types/account.go
  persistence/types/base_actor.go
  persistence/types/gov.go
  persistence/types/persistence_genesis.go
  persistence/types/shared_sql.go
  persistence/validator.go
Labels: code health

#356 [quick change] remove codeowners
  .github/CODEOWNERS
Labels: tooling

#353 [P2P] Remove topic from messaging - Issue #267
  Makefile
  app/client/cli/debug.go
  consensus/consensus_tests/utils_test.go
  consensus/debugging.go
  consensus/helpers.go
  consensus/module.go
  go.mod
  p2p/CHANGELOG.md
  p2p/module.go
  p2p/module_raintree_test.go
  p2p/raintree/network.go
  persistence/debug.go
  shared/CHANGELOG.md
  shared/bus.go
  shared/debug/proto/debug_message.proto
  shared/debug/proto/events.proto
  shared/messaging/events.go
  shared/messaging/messages.go
  shared/messaging/messages_test.go
  shared/messaging/proto/debug_message.proto
  shared/messaging/proto/events.proto
  shared/messaging/proto/pocket_envelope.proto
  shared/messaging/utils.go
  shared/messaging/utils_test.go
  shared/modules/bus_module.go
  shared/modules/consensus_module.go
  shared/modules/p2p_module.go
  shared/modules/persistence_module.go
  shared/node.go
Labels: p2p

#301 Logger module #164
  .github/workflows/main.yml
  Makefile
  app/client/cli/debug.go
  build/config/config1.json
  build/config/config2.json
  build/config/config3.json
  build/config/config4.json
  consensus/consensus_tests/utils_test.go
  go.mod
  go.sum
  logger/module.go
  logger/proto/logger_config.proto
  runtime/config.go
  shared/bus.go
  shared/modules/bus_module.go
  shared/modules/logger_module.go
  shared/modules/module.go
  shared/modules/types.go
  shared/node.go
Labels: core, code health, priority:medium, tooling, observability

#359 [P2P] Remove topic from messaging - Issue #267 - NITS
  shared/messaging/envelope.go
  shared/messaging/envelope_test.go
  shared/messaging/messages.go
  shared/node.go
Labels: p2p

#252 [Core] StateHash Interfaces & Diagrams
  consensus/CHANGELOG.md
  consensus/block.go
  consensus/consensus_tests/utils_test.go
  consensus/debugging.go
  consensus/helpers.go
  consensus/hotstuff_leader.go
  consensus/hotstuff_replica.go
  consensus/module.go
  consensus/pacemaker.go
  persistence/CHANGELOG.md
  persistence/block.go
  persistence/context.go
  persistence/db.go
  persistence/debug.go
  persistence/genesis.go
  persistence/module.go
  persistence/test/module_test.go
  shared/CHANGELOG.md
  shared/docs/PROTOCOL_STATE_HASH.md
  shared/docs/flows/AppHash.md
  shared/modules/doc/CHANGELOG.md
  shared/modules/persistence_module.go
  shared/modules/utility_module.go
  utility/block.go
  utility/context.go
  utility/doc/CHANGELOG.md
  utility/test/block_test.go
  utility/test/module_test.go
Labels: core, consensus, utility

#342 [Consensus] State Sync - Block by Block Design (issue-#125)
  README.md
  consensus/doc/CHANGELOG.md
  consensus/doc/PROTOCOL_STATE_SYNC.md
  consensus/state_sync/state_sync.go
Labels: documentation, core, consensus
