Repository pokt-network/pocket, pull requests merged in 2022-09, with the labels that each got.

#218 [TECHDEBT] Replace `log.Fatal(fmt.Sprintf))` with `log.FatalF()`
  persistence/genesis.go
  persistence/test/application_test.go
  persistence/test/fisherman_test.go
  persistence/test/service_node_test.go
  persistence/test/validator_test.go
Labels: code health

#217 Fix paths for persistence docs
  README.md
  persistence/docs/CHANGELOG.md
  persistence/docs/README.md
Labels: documentation, persistence

#196 References and resources for learning 🧱 ⛓️
  docs/learning/README.md
Labels: documentation

#220 [TECHDEBT] Consolidate `GetHashStringFromBytes`
  p2p/raintree/utils.go
  shared/crypto/sha3.go
  utility/doc/CHANGELOG.md
  utility/types/mempool.go
  utility/types/transaction.go
Labels: code health

#207 Add make targets for config & genesis generation Issue #182
  .gitignore
  Makefile
  build/config/README.md
  build/config/main.go
Labels: tooling

#167 [Persistence] Base Tx Indexer Implementation (Issue#151)
  Makefile
  go.mod
  go.sum
  persistence/kvstore/kvstore.go
  shared/codec/codec.go
  shared/indexer/indexer.go
  shared/indexer/indexer_test.go
  shared/indexer/proto/transaction_indexer.proto
  shared/modules/telemetry_module.go
Labels: core, persistence, priority:medium

#223 [TECHDEBT] Break types into their respective files
  Makefile
  p2p/types/addrbook.go
  p2p/types/addrlist.go
  p2p/types/network.go
  p2p/types/network_peer.go
  p2p/types/transport.go
  shared/modules/bus_module.go
  shared/modules/consensus_module.go
  shared/modules/p2p_module.go
  shared/modules/persistence_module.go
  shared/modules/telemetry_module.go
  shared/modules/utility_module.go
Labels: p2p, code health

#219 [TECHDEBT] Consolidated PostgresContext and PostgresDB (#149)
  p2p/module_raintree_test.go
  persistence/CHANGELOG.md
  persistence/account.go
  persistence/block.go
  persistence/context.go
  persistence/db.go
  persistence/genesis.go
  persistence/gov.go
  persistence/kvstore/kvstore.go
  persistence/module.go
  persistence/shared_sql.go
  persistence/test/setup_test.go
  utility/gov.go
Labels: persistence, code health

#243 [P2P]: BenchmarkAddrBookUpdates updated to actually update the addressbook - Issue #242
  p2p/raintree/addrbook_utils_test.go
Labels: code health, tooling

#240 [One line change] Fix order in `make develop_test`
  Makefile
Labels: code health

#248 [One line change] Cleanup mocks before generating
  Makefile
Labels: bug

#225 [TECHDEBT] Utility Module testing package (issue-#224)
  utility/account.go
  utility/actor.go
  utility/block.go
  utility/context.go
  utility/doc/CHANGELOG.md
  utility/gov.go
  utility/test/account_test.go
  utility/test/actor_test.go
  utility/test/block_test.go
  utility/test/gov_test.go
  utility/test/module_test.go
  utility/test/transaction_test.go
  utility/transaction.go
  utility/types/error.go
  utility/types/vote_test.go
Labels: code health

#254 [TECHDEBT] Cleanup Remaining *non-blocked* TODOs in the Utility Module (Issue #229)
  consensus/CHANGELOG.md
  consensus/block.go
  utility/actor.go
  utility/doc/CHANGELOG.md
  utility/gov.go
  utility/test/gov_test.go
  utility/test/module_test.go
  utility/types/error.go
  utility/types/message.go
  utility/types/vote.go
Labels: code health

#198 [Tooling] Flaky tests - Issue #192
  .github/workflows/main.yml
  Makefile
  app/pocket/main.go
  consensus/consensus_tests/hotstuff_test.go
  consensus/consensus_tests/pacemaker_test.go
  consensus/consensus_tests/utils_test.go
  consensus/debugging.go
  consensus/helpers.go
  consensus/module.go
  consensus/pacemaker.go
  go.mod
  go.sum
  shared/CHANGELOG.md
  shared/README.md
  shared/bus.go
  shared/modules/bus_module.go
  shared/modules/consensus_module.go
  shared/node.go
Labels: core, consensus, tooling

#247 [TECHDEBT] Add TestUtilityCodec in the Shared Module (issue-#231)
  Makefile
  shared/CHANGELOG.md
  shared/codec/codec_test.go
  shared/codec/proto/codec_test.proto
Labels: code health

#236 [TECHDEBT] Utility Module, remove `DELETE` *actor* 'No-op' code
  shared/modules/persistence_module.go
  utility/actor.go
  utility/block.go
  utility/doc/CHANGELOG.md
  utility/test/actor_test.go
  utility/types/error.go
Labels: code health

#238 [TECHDEBT] Persistence Module, remove `DELETE` *actor* 'No-op' code
  persistence/README.md
  persistence/application.go
  persistence/docs/CHANGELOG.md
  persistence/docs/README.md
  persistence/fisherman.go
  persistence/service_node.go
  persistence/test/generic_test.go
  persistence/types/protocol_actor.go
  persistence/types/shared_sql.go
  persistence/validator.go
Labels: core, code health
