Repository pokt-network/pocket, pull requests merged in 2023-08, with the labels that each got.

#957 DevLog 12
  docs/devlog/devlog12.md
Labels: documentation, waiting-for-review, small

#952 [Utility] servicer signs relays
  runtime/configs/proto/servicer_config.proto
  utility/module_enable_actors_test.go
  utility/servicer/module.go
  utility/servicer/module_test.go
Labels: utility, waiting-for-review, medium

#940 [LocalNet] Fix metrics scraping
  build/localnet/Tiltfile
  charts/pocket/templates/statefulset.yaml
Labels: infra, waiting-for-review, small

#874 [E2E Test] Utilities for State Sync Test
  .github/workflows/main.yml
  .gitignore
  .tiltignore
  Makefile
  app/client/cli/debug.go
  build/config/README.md
  build/docs/CHANGELOG.md
  build/localnet/README.md
  build/localnet/Tiltfile
  build/scripts/watch.sh
  build/scripts/watch_build.sh
  consensus/module_consensus_debugging.go
  docs/demos/iteration_3_end_to_end_tx.md
  docs/development/FAQ.md
  docs/development/README.md
  e2e/README.md
  e2e/docs/E2E_ADR.md
  e2e/tests/account.feature
  e2e/tests/debug.feature
  e2e/tests/node.go
  e2e/tests/query.feature
  e2e/tests/root.feature
  e2e/tests/state_sync.feature
  e2e/tests/steps_init_test.go
  e2e/tests/tilt_helpers.go
  e2e/tests/validator.feature
  e2e/tests/validator.go
  go.mod
  persistence/docs/CHANGELOG.md
  persistence/docs/README.md
  shared/modules/doc/CHANGELOG.md
  telemetry/README.md
Labels: consensus, e2e-devnet-test, large

#968 Update servicer private key for config.validator1.json
  build/config/config.validator1.json
  ibc/store/provable_store_test.go
  runtime/manager_test.go
Labels: bug, waiting-for-review, small

#955 [Documentation] Code review guidelines & learning resources
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/development/CODE_GUIDELINES.md
  docs/development/CODE_REVIEW_GUIDELINES.md
  docs/development/README.md
  docs/learning/README.md
Labels: documentation, waiting-for-review, docs, medium

#970 chore: restore origin gocuke and update
  go.mod
  go.sum
Labels: code health, tooling, push-image, waiting-for-review, e2e-devnet-test, small
