Repository pokt-network/pocket, pull requests merged in 2023-05, with the labels that each got.

#721 [Persistence] Index Transactions by Transaction Hash
  consensus/doc/CHANGELOG.md
  consensus/module.go
  persistence/block.go
  persistence/context.go
  persistence/docs/CHANGELOG.md
  persistence/indexer/doc/README.md
  persistence/indexer/indexer.go
  persistence/indexer/indexer_test.go
  persistence/state.go
  persistence/test/benchmark_state_test.go
  persistence/test/state_test.go
  shared/CHANGELOG.md
  shared/core/types/idx_tx.go
  shared/core/types/proto/idx_tx.proto
  shared/core/types/tx_result.go
  shared/modules/persistence_module.go
  utility/doc/CHANGELOG.md
  utility/types/idx_tx.go
  utility/unit_of_work/module.go
  utility/unit_of_work/transaction.go
  utility/unit_of_work/transaction_test.go
  utility/unit_of_work/uow_leader.go
Labels: persistence, large, waiting-for-review

#739 [Testing] [Tooling] Replace godog with gocuke
  e2e/tests/steps_init_test.go
  go.mod
  go.sum
  shared/k8s/debug.go
Labels: tooling, testing, medium, waiting-for-review

#736 [Persistence] Refactors BlockStore
  consensus/doc/CHANGELOG.md
  consensus/e2e_tests/utils_test.go
  persistence/blockstore/block_store.go
  persistence/context.go
  persistence/docs/CHANGELOG.md
  persistence/kvstore/kvstore.go
  persistence/module.go
  shared/modules/doc/CHANGELOG.md
  shared/modules/persistence_module.go
Labels: medium, waiting-for-review, e2e-devnet-test

#738 [Docs] Updates pull request template to include E2E items in Testing checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, code health, small, waiting-for-review

#758 [Tooling] Ran gosimports on the entire repo
  .golangci.yml
  Makefile
  app/client/cli/debug.go
  app/client/cli/docgen/main.go
  app/client/cli/keys.go
  app/client/debug.go
  build/debug_keybase/main.go
  consensus/leader_election/sortition/sortition.go
  consensus/leader_election/sortition/sortition_test.go
  consensus/leader_election/vrf/vrf.go
  consensus/leader_election/vrf/vrf_test.go
  e2e/tests/steps_init_test.go
  p2p/background/kad_discovery_baseline_test.go
  p2p/background/router.go
  p2p/background/router_test.go
  p2p/config/config.go
  p2p/module.go
  p2p/module_raintree_test.go
  p2p/module_test.go
  p2p/providers/peerstore_provider/peerstore_provider.go
  p2p/raintree/peers_manager_test.go
  p2p/raintree/router.go
  p2p/raintree/router_test.go
  p2p/transport_encryption_test.go
  p2p/types/network_peer.go
  p2p/types/peers_view_test.go
  p2p/utils/host.go
  p2p/utils/logging.go
  p2p/utils/peer_conversion.go
  p2p/utils/url_conversion_test.go
  p2p/utils_test.go
  persistence/gov.go
  persistence/test/fisherman_test.go
  persistence/test/generic_test.go
  persistence/test/servicer_test.go
  persistence/test/validator_test.go
  persistence/types/gov.go
  rpc/module.go
  runtime/configs/config.go
  runtime/test_artifacts/generator.go
  shared/crypto/slip/slip.go
  state_machine/fsm.go
  utility/main_test.go
  utility/session.go
  utility/session_test.go
Labels: core, code health, medium, waiting-for-review

#760 [Comment] Inform user that LocalNet is needed for E2E tests
  Makefile
  build/localnet/README.md
Labels: code health, testing, small, waiting-for-review

#761 [Documentation] Minor additions to learning & development guide
  README.md
  docs/development/README.md
  docs/learning/README.md
Labels: documentation, small, waiting-for-review, docs

#765 Update PULL_REQUEST_TEMPLATE.md - summary
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, small, waiting-for-review

#740 Refactoring the assignment order of the RunCommand function in validatorPod
  e2e/tests/validator.go
Labels: testing, waiting-for-review, small

#770 [CI] Add inline error check linter
  app/client/keybase/keystore.go
  build/linters/errs.go
  consensus/hotstuff_replica.go
  persistence/gov.go
  persistence/kvstore/kvstore.go
  shared/crypto/ed25519.go
  shared/crypto/keys.go
Labels: infra, waiting-for-review, gpt review, small

#768 [Tooling] fix: changelog validation exits properly on failure
  .github/workflows/changelog-verify.yml
Labels: bug, code health, tooling, waiting-for-review, small

#772 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, waiting-for-review, small

#767 [Helm] Add ServiceMonitor to the helm chart
  .github/workflows/e2e-test.yml
  .github/workflows/main.yml
  charts/CHANGELOG.md
  charts/pocket/README.md
  charts/pocket/templates/service-monitor.yaml
  charts/pocket/templates/statefulset.yaml
  charts/pocket/values.yaml
Labels: infra, waiting-for-review, e2e-devnet-test, medium

#779 add public keys to private-keys.yaml
  build/localnet/manifests/private-keys.yaml
Labels: infra, waiting-for-review, large

#783 [BUG] Int casting issue when sending tx
  p2p/CHANGELOG.md
  p2p/module.go
  p2p/module_raintree_test.go
  p2p/raintree/peerstore_utils.go
Labels: bug, waiting-for-review, small

#774 [Persistence] Refactors BlockStore Interface
  consensus/doc/CHANGELOG.md
  consensus/e2e_tests/utils_test.go
  consensus/state_sync/server.go
  persistence/block.go
  persistence/blockstore/block_store.go
  persistence/context.go
  persistence/debug.go
  persistence/docs/CHANGELOG.md
  persistence/test/state_test.go
  rpc/doc/CHANGELOG.md
  rpc/handlers_query.go
Labels: persistence, code health, waiting-for-review, e2e-devnet-test, cl validate, medium

#764 [k8s] Rename `client` to `p1` in k8s localnet
  app/client/cli/cmd.go
  app/client/doc/CHANGELOG.md
  build/Dockerfile.debian.dev
  build/docs/CHANGELOG.md
  build/localnet/Tiltfile
  e2e/docs/CHANGELOG.md
  e2e/tests/validator.go
Labels: waiting-for-review, e2e-devnet-test, small

#782 [Testing] [Tooling] chore: replace `gocuke` & `go-mockdns` in go.mod
  go.mod
  go.sum
Labels: tooling, testing, waiting-for-review, small

#788 Fix places where we request a password and don't check the nonInterac…
  app/client/cli/actor.go
  app/client/cli/gov.go
  app/client/doc/CHANGELOG.md
Labels: client, waiting-for-review, small

#787 change gitsha of private-keys.yaml
  build/debug_keybase/73e3f85e886d74e4cea14458f39a338a.md5
Labels: infra, waiting-for-review, small

#734 [Utility] E2E Feature Path Template
  Makefile
  utility/doc/CHANGELOG.md
  utility/doc/E2E_FEATURE_PATH_TEMPLATE.md
Labels: utility, waiting-for-review, docs, medium

#792 Remove coverage prep stage as this corrupts the coverage report
  .github/workflows/main.yml
Labels: bug, waiting-for-review, small

#763 [P2P] refactor: message handling
  Makefile
  p2p/CHANGELOG.md
  p2p/config/config.go
  p2p/module.go
  p2p/module_raintree_test.go
  p2p/raintree/logging.go
  p2p/raintree/peers_manager_test.go
  p2p/raintree/router.go
  p2p/raintree/testutil.go
  p2p/transport_encryption_test.go
  p2p/types/router.go
Labels: p2p, waiting-for-review, gpt review, large
